apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- ingress.yaml
- catalog-deployment.yaml
- catalog-service.yaml
- orders-deployment.yaml
- orders-service.yaml
- payments-deployment.yaml
- payments-service.yaml
- users-deployment.yaml
- users-service.yaml
- notifications-deployment.yaml
- notifications-service.yaml
- gateway-deployment.yaml
- gateway-service.yaml
